// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://felmkymspbhydbhrqxog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlbG1reW1zcGJoeWRiaHJxeG9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1NzQwOTYsImV4cCI6MjA3OTE1MDA5Nn0.io42QFoDQvsQNuanfR_BDYjX7o6rsRvN7FJy9B-mgA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});